#lang racket/unit
(require "../main.rkt")
(import)
(export plugin^)
(define version "0.1")
(define dependencies '())
(define description "Sayer")
(define (msg s)
  (printf "Sayer ~a: ~a" version s))
(define (load!)
  ;; (printf "Sayer ~a loaded.\n" version)
  (msg "loaded")
  )
(define (unload!)
  (printf "Sayer ~a unloaded.\n" version))
